#+TITLE: BOLT #7: P2P Node and Channel Discovery

* Channel announcement

** Receiving [2/6]

   - [ ] MUST verify the integrity AND authenticity of the message by verifying the signatures.

   - [ ] if there is an unknown even bit in the ~features~ field:
     MUST NOT attempt to route messages through the channel.

   - [X] if the ~short_channel_id~'s output does NOT correspond to a P2WSH (using ~bitcoin_key_1~ and ~bitcoin_key_2~, as specified in BOLT #3) OR the output is spent:
     MUST ignore the message. ([[file:~/dev/scala/lnz/src/main/scala/proto/bolt/validate.scala::Channel announcement tx output][ref1]], [[file:~/dev/scala/lnz/src/main/scala/peer.scala::Ignore spent tx output][ref2]])

   - [X] if the specified ~chain_hash~ is unknown to the receiver:
     MUST ignore the message. ([[file:../../src/main/scala/proto/bolt/validate.scala::Channel announcement chain hash][ref1]], [[file:../../src/main/scala/peer.scala::Ignore unknown chain messages][ref2]])

   - [ ] otherwise:
     
     - [ ] if ~bitcoin_signature_1~, ~bitcoin_signature_2~, ~node_signature_1~ OR ~node_signature_2~ are invalid OR NOT correct:
       SHOULD fail the connection.
       
     - [ ] otherwise:
       
       - [ ] if ~node_id_1~ OR ~node_id_2~ are blacklisted:
	 SHOULD ignore the message.
	 
       - [ ] otherwise:
	 
	 - [ ] if the transaction referred to was NOT previously announced as a channel:
	   
	   - [ ] SHOULD queue the message for rebroadcasting.
	     
	   - [ ] MAY choose NOT to for messages longer than the minimum expected length.
	     
       - [ ] if it has previously received a valid ~channel_announcement~, for the same transaction, in the same block, but for a different node_id_1 or node_id_2:
	 SHOULD blacklist the previous message's ~node_id_1~ and ~node_id_2~, as well as this ~node_id_1~ and ~node_id_2~ AND forget any channels connected to them.
	 
       - [ ] otherwise:
	 SHOULD store this ~channel_announcement~.
	 
   - [ ] once its funding output has been spent OR reorganized out:
     SHOULD forget a channel.
